### ISSUE TITLE
关于 CJK ctex 的疑问

### ISSUE THREAD

**Issue by ZhangYanTJU** [xnth97/TJUThesisLatexTemplate#3]
你好，你的介绍里边写的：
`移除 CJK，使用 ctex`
我对这两个不太熟悉。但我看到：
format.tex 里边，你把 CJKfamily 字体注释了
package.tex 里边，你把 \usepackage{ctex} 注释了，加入了 \usepackage{CJK}
我疑惑的是，为什么要在这里加入 CJK 呢？

**Comment by pdwangchao** [comment]
移除CJK使用ctex是一个亮点，我当时为了兼容CJK，使用VMWARE虚拟了一个XP系统 安装的CTEX，用学校的模板，这样其实挺方便的，题主也可以考虑。天大的模板里有一些设定已经不符合现行的学校规范，我只改动了博士论文模板部分，等我再完善一下会发到github里。

**Comment by ZhangYanTJU** [comment]
谢谢两位！
我也想弄一个更新的博士论文的模板呢，留给自己将来使用 :）
既然前辈 @pdwangchao 已经有了，那最好不过啦 👍

**Comment by ZhangYanTJU** [comment]
@pdwangchao 一直在关注这个，因为我将来的博士毕业论文实在不想用 Word 写啊。您有空的话，能更新一下您修改后的模板吗？

**Comment by pdwangchao** [comment]
好的，我1月15号左右更新一下。




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            pdwangchao
                            
                            
                                
                                    邮箱：pdwangchao@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年01月03日 21:23，Yan Zhang 写道： @pdwangchao 一直在关注这个，因为我将来的博士毕业论文实在不想用 Word 写啊。您有空的话，能更新一下您修改后的模板吗？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xnth97/TJUThesisLatexTemplate","title":"xnth97/TJUThesisLatexTemplate","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xnth97/TJUThesisLatexTemplate"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ZhangYanTJU in #3: @pdwangchao 一直在关注这个，因为我将来的博士毕业论文实在不想用 Word 写啊。您有空的话，能更新一下您修改后的模板吗？"}],"action":{"name":"View Issue","url":"https://github.com/xnth97/TJUThesisLatexTemplate/issues/3#issuecomment-451141399"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xnth97/TJUThesisLatexTemplate/issues/3#issuecomment-451141399",
"url": "https://github.com/xnth97/TJUThesisLatexTemplate/issues/3#issuecomment-451141399",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pdwangchao** [comment]
已更新，https://github.com/pdwangchao/TJUthesis_Ctex_xp/blob/master/README.md

**Comment by ZhangYanTJU** [comment]
@pdwangchao 十分感谢！祝顺利！
